services:
  servuo:
    build:
      context: .
    restart: always
    volumes:
      - servuo:${CONTAINER_SERVUO_DIR}
      - game_files:${CONTAINER_SERVUO_DIR}
    ports:
    - "2593:2593"
    command: make

volumes:
  servuo: {}
  game_files: {}
