services:
  servuo:
    build:
      context: .
    restart: always
    volumes:
      - ./data:/UO
      - /Users/davelens/Applications/UO:/GAME
    network_mode: host
#    mem_limit: 2048m
#    ports:
#    - "2593:2593/tcp"
    command: make
