services:
  servuo:
    build:
      context: .
    restart: always
    volumes:
      - ./servuo:/servuo
      - ./game_files:/game_files
    ports:
    - "2593:2593"
    command: make

volumes:
  servuo: {}
  game_files: {}
